# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('NIP', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('adress', models.CharField(max_length=200)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('adnotations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Assistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pics/')),
                ('phone_number', models.IntegerField()),
                ('date_birth', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='customer_assistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapp.Customer_Assistant'),
        ),
    ]
