# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='com-pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_assistant',
            name='photo',
            field=models.ImageField(upload_to='cu-pics/'),
        ),
    ]
