# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0003_auto_20170213_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
