# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0004_auto_20170213_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adnotations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='/home/lukasz/Dokumenty/Django/crm/crm/../media'),
        ),
        migrations.AlterField(
            model_name='customer_assistant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='/home/lukasz/Dokumenty/Django/crm/crm/../media'),
        ),
    ]
