# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0005_auto_20170214_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='customer_assistant',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer_assistant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
