# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0006_auto_20170214_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_assistant',
            name='date_birth',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer_assistant',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
    ]
