# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0007_auto_20170214_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_assistant',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
