# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 02:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapp', '0010_auto_20170215_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='NIP',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='NIP powinien zawierać 10 cyfr.', regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Numer telefonu powinien zawierać co najmniej 9 cyfr.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
